before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - 386 
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: 386
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: 386
archives:
  - replacements:
      386: i386
changelog:
  sort: asc
# dockers:
#   - dockerfile: goreleaser.dockerfile
#   - image_templates:
#     - "gcr.io/rssnyder/discord-bot:{{ .Tag }}"
#     - "gcr.io/rssnyder/discord-bot:latest"
#   - build_flag_templates:
#     - "--pull"
#     - "--label=org.opencontainers.image.created={{.Date}}"
#     - "--label=org.opencontainers.image.title={{.ProjectName}}"
#     - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#     - "--label=org.opencontainers.image.version={{.Version}}"
#     - "--label=org.opencontainers.image.source=https://github.com/rssnyder/discord-bot"
