on:
  workflow_dispatch:
  release:
    types:
      - published
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  go-releaser:
    uses: rssnyder/actions/.github/workflows/go-releaser.yml@main
    with:
      go-version: 1.19
  docker-build-and-push:
    needs: go-releaser
    uses: rssnyder/actions/.github/workflows/docker-build-and-push.yml@main
